In [88]:
import numpy as np

Data Creation

In [89]:
student = np.array(["Alia", "Riya", "Ram", "Priya", "Eve", "Don"])
subject = np.array(["Physics", "Chemistry", "English", "Maths"])
marks = np.array([
    [90, 65, 95, 91],
    [80, 75, 90, 85],
    [95, 89, 94, 87],
    [76, 64, 68, 87],
    [89, 85, 91, 85],
    [88, 71, 60, 40]])

print(student)
print(subject)
print(marks)





['Alia' 'Riya' 'Ram' 'Priya' 'Eve' 'Don']
['Physics' 'Chemistry' 'English' 'Maths']
[[90 65 95 91]
 [80 75 90 85]
 [95 89 94 87]
 [76 64 68 87]
 [89 85 91 85]
 [88 71 60 40]]


Data Exploration

In [90]:
print(student.ndim)
print(subject.ndim)
print(marks.ndim)

1
1
2


In [91]:
print(student.size)
print(subject.size)
print(marks.size)

6
4
24


In [92]:
print(student.shape)
print(subject.shape)
print(marks.shape)

(6,)
(4,)
(6, 4)


Data Transformation

In [93]:
print(marks.flatten())


[90 65 95 91 80 75 90 85 95 89 94 87 76 64 68 87 89 85 91 85 88 71 60 40]


In [94]:
print(marks.reshape(12,2))

[[90 65]
 [95 91]
 [80 75]
 [90 85]
 [95 89]
 [94 87]
 [76 64]
 [68 87]
 [89 85]
 [91 85]
 [88 71]
 [60 40]]


In [95]:
print(marks.T)

[[90 80 95 76 89 88]
 [65 75 89 64 85 71]
 [95 90 94 68 91 60]
 [91 85 87 87 85 40]]


In [96]:
print(np.flip(marks))

[[40 60 71 88]
 [85 91 85 89]
 [87 68 64 76]
 [87 94 89 95]
 [85 90 75 80]
 [91 95 65 90]]


Data Combination

In [97]:
student = np.array(['Alia',"Riya","Ram"])
marks = np.array([[90, 65, 95, 91],
    [80, 75, 90, 85],
    [95, 89, 94, 87]])
student_1 = np.array(["Siya"])
marks_1 = np.array([[75,80,90,89]])

student = np.concatenate((student,student_1))
marks = np.concatenate((marks,marks_1))


In [98]:
print(student)

['Alia' 'Riya' 'Ram' 'Siya']


In [99]:
print(marks)

[[90 65 95 91]
 [80 75 90 85]
 [95 89 94 87]
 [75 80 90 89]]


In [100]:
marks= marks.reshape(-1)
print(marks)
np.split(marks,4)

[90 65 95 91 80 75 90 85 95 89 94 87 75 80 90 89]


[array([90, 65, 95, 91]),
 array([80, 75, 90, 85]),
 array([95, 89, 94, 87]),
 array([75, 80, 90, 89])]

Data Modification

In [101]:
marks[4] = 40
print(marks)

[90 65 95 91 40 75 90 85 95 89 94 87 75 80 90 89]


In [102]:
q = np.delete(marks,4)
print(q)

[90 65 95 91 75 90 85 95 89 94 87 75 80 90 89]


In [103]:
print(marks)
np.unique(marks)

[90 65 95 91 40 75 90 85 95 89 94 87 75 80 90 89]


array([40, 65, 75, 80, 85, 87, 89, 90, 91, 94, 95])

DataType Handling

In [104]:
print(marks.dtype)
print(marks.astype(dtype=float))
print(marks.astype(dtype=str))

int64
[90. 65. 95. 91. 40. 75. 90. 85. 95. 89. 94. 87. 75. 80. 90. 89.]
['90' '65' '95' '91' '40' '75' '90' '85' '95' '89' '94' '87' '75' '80'
 '90' '89']


Copy vs View Behavior

In [105]:
a = marks.copy()
a[0] = 99
print(a)

[99 65 95 91 40 75 90 85 95 89 94 87 75 80 90 89]


In [106]:
b = marks.view()
b[0] = 100
print(b)

[100  65  95  91  40  75  90  85  95  89  94  87  75  80  90  89]
